
import { Navbar } from '@/components/Navbar';
import { AuthContext } from '@/context/AuthContext';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useContext , useEffect } from 'react';

export default function Home() {  
  return (
    <>
      <Head>
        <title>PhotosHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
      </main>

    </>
  );
};
