
import { Hero } from '@/components/Hero';
import { Navbar } from '@/components/Navbar';
import { AuthContext } from '@/context/AuthContext';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useContext , useEffect } from 'react';

export default function Home() {  

  const image = "https://cdn.wallpaperhub.app/cloudcache/3/e/e/2/2/a/3ee22a464c4eb2183e7816306ca2976bcd541d25.jpg";

  return (
    <>
      <Head>
        <title>PhotosHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero image={image} imageId={"1"} subtitle={"Image"} title={"Microsoft"} key={image} />
      </main>

    </>
  );
};
